### ISSUE TITLE
Verification Page

### ISSUE THREAD

**Issue by TheRykerJ** [FlagClicked/FlagClicked#21] opened 2021-03-17 13:47 UTC
I know Jeffalo has a thing on Ocular that requires you to verify with a Scratch account,  and I was wondering if we could do this with When Flag Clicked or if that is even necessary.

**Comment by retronbv** [comment] 2021-03-17 13:49
We could use fluffy scratch

**Comment by TheRykerJ** [comment] 2021-03-17 13:51
> We could use fluffy scratch

Oh I think I have heard of that. Pretty sure that is what Ocular uses.

**Comment by TheColaber** [comment] 2021-03-17 13:54
Duplicate of #3

**Closed by TheColaber** 2021-03-17 13:54 UTC
Labels: enhancement
